name: test-flow

on: [pull_request]

jobs:
  sendhook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Run python script
      run: |
        pip install requests
        python .github/workflows/scripts/onpull_request.py "${{secrets.WEBHOOK_URL}}" "${{toJSON(github.repository)}}" "${{github.event.action}}" "${{github.event.pull_request.title}}" "${{github.event.pull_request.user.login}}" "${{github.events.pull_request.url}}" 